# Generated by Django 5.2 on 2025-05-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
