# Generated by Django 5.2 on 2025-05-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_remove_producto_imagen_url_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='color',
            field=models.CharField(choices=[('Rojo', 'Rojo'), ('Azul', 'Azul'), ('Verde', 'Verde'), ('Negro', 'Negro'), ('Blanco', 'Blanco'), ('Gris', 'Gris'), ('Amarillo', 'Amarillo'), ('Morado', 'Morado')], default='Negro', max_length=20),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidades',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
