# Generated by Django 5.2.1 on 2025-06-03 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_pedido'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
