# Generated by Django 5.0.2 on 2024-02-20 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_cliente_options_alter_direccion_options_and_more'),
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={'verbose_name': 'Compra', 'verbose_name_plural': 'Compras'},
        ),
        migrations.AlterModelOptions(
            name='itemcompra',
            options={'verbose_name': 'ItemCompra', 'verbose_name_plural': 'ItemCompras'},
        ),
        migrations.AlterModelOptions(
            name='marca',
            options={'verbose_name': 'Marca', 'verbose_name_plural': 'Marcas'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='valoracion',
            options={'verbose_name': 'Valoracion', 'verbose_name_plural': 'Valoraciones'},
        ),
        migrations.AddField(
            model_name='compra',
            name='direccion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.direccion', verbose_name='Dirección'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compra',
            name='tarjeta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.tarjeta', verbose_name='Tarjeta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compra',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='itemcompra',
            name='compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.compra', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='itemcompra',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.producto', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='valoracion',
            name='comentario',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='valoracion',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.producto', verbose_name='Producto'),
        ),
    ]
