# Generated by Django 5.0.2 on 2024-02-20 01:16

import creditcards.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='direccion',
            options={'verbose_name': 'Direccion', 'verbose_name_plural': 'Direcciones'},
        ),
        migrations.AlterModelOptions(
            name='tarjeta',
            options={'verbose_name': 'Tarjeta', 'verbose_name_plural': 'Tarjetas'},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='ciudad',
            field=models.CharField(max_length=30, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='codigo_postal',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999)], verbose_name='Código postal'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='instrucciones',
            field=models.TextField(blank=True, null=True, verbose_name='Instrucciones'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='linea_de_direccion',
            field=models.CharField(max_length=150, verbose_name='Línea de dirección'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='numero_de_telefono',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Numero de telefono'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='provincia',
            field=models.CharField(max_length=30, verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='cc_expiry',
            field=creditcards.models.CardExpiryField(verbose_name='Fecha de expiración'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='cc_number',
            field=models.CharField(validators=[django.core.validators.MinLengthValidator(12), django.core.validators.MaxLengthValidator(19)], verbose_name='Número de tarjeta'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='titular',
            field=models.CharField(max_length=100, verbose_name='Titular'),
        ),
    ]
