# Generated by Django 5.2 on 2025-05-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_carrito_itemcarrito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcarrito',
            name='personalizacion',
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='personalizado',
            field=models.BooleanField(default=False),
        ),
    ]
