# Generated by Django 5.2 on 2025-05-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_remove_itemcarrito_personalizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ventas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
